// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type LandingPageDocumentDataSlicesSlice =
  | FrequentlyAskedSlice
  | BookingProcessSlice
  | RoomsGridSlice
  | BuildingStorySlice
  | StatStripSlice
  | HeroSectionSlice;

/**
 * Content for landing page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *landing page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *landing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * landing page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

export type AllDocumentTypes = LandingPageDocument;

/**
 * Primary content in *BookingProcess → Default → Primary*
 */
export interface BookingProcessSliceDefaultPrimary {
  /**
   * Eyebrow field in *BookingProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. How It Works
   * - **API ID Path**: booking_process.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *BookingProcess → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: booking_process.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *BookingProcess → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short supporting copy
   * - **API ID Path**: booking_process.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Label field in *BookingProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Start Booking
   * - **API ID Path**: booking_process.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *BookingProcess → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where the CTA button should go
   * - **API ID Path**: booking_process.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *BookingProcess → Items*
 */
export interface BookingProcessSliceDefaultItem {
  /**
   * Step Number field in *BookingProcess → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 01 (optional, falls back to index)
   * - **API ID Path**: booking_process.items[].step_number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_number: prismic.KeyTextField;

  /**
   * Icon field in *BookingProcess → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_process.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Step Title field in *BookingProcess → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Browse & Select
   * - **API ID Path**: booking_process.items[].step_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_title: prismic.KeyTextField;

  /**
   * Step Description field in *BookingProcess → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short explanation of this step
   * - **API ID Path**: booking_process.items[].step_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  step_description: prismic.RichTextField;
}

/**
 * Default variation for BookingProcess Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BookingProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BookingProcessSliceDefaultPrimary>,
  Simplify<BookingProcessSliceDefaultItem>
>;

/**
 * Slice variation for *BookingProcess*
 */
type BookingProcessSliceVariation = BookingProcessSliceDefault;

/**
 * BookingProcess Shared Slice
 *
 * - **API ID**: `booking_process`
 * - **Description**: A numbered, step-by-step walkthrough of how the booking process works.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BookingProcessSlice = prismic.SharedSlice<
  "booking_process",
  BookingProcessSliceVariation
>;

/**
 * Item in *BuildingStory → Default → Primary → timeline*
 */
export interface BuildingStorySliceDefaultPrimaryTimelineItem {
  /**
   * tag field in *BuildingStory → Default → Primary → timeline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 1930's
   * - **API ID Path**: building_story.default.primary.timeline[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;

  /**
   * title field in *BuildingStory → Default → Primary → timeline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Built on Prince Edward Road West
   * - **API ID Path**: building_story.default.primary.timeline[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *BuildingStory → Default → Primary → timeline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Raised as a three-storey walk-up in the pre-war style that still defines this stretch of Mong Kok.
   * - **API ID Path**: building_story.default.primary.timeline[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *BuildingStory → Default → Primary*
 */
export interface BuildingStorySliceDefaultPrimary {
  /**
   * eyebrow field in *BuildingStory → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: THE BUILDING'S STORY
   * - **API ID Path**: building_story.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * heading field in *BuildingStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Before it was dwell, it was Mang Kok
   * - **API ID Path**: building_story.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * description field in *BuildingStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This address has been part of the neighbourhood far longer than the brand on the door. Here's the short version.
   * - **API ID Path**: building_story.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * timeline field in *BuildingStory → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: building_story.default.primary.timeline[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  timeline: prismic.GroupField<
    Simplify<BuildingStorySliceDefaultPrimaryTimelineItem>
  >;

  /**
   * panel_image field in *BuildingStory → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: building_story.default.primary.panel_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  panel_image: prismic.ImageField<never>;
}

/**
 * Default variation for BuildingStory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BuildingStorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BuildingStorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BuildingStory*
 */
type BuildingStorySliceVariation = BuildingStorySliceDefault;

/**
 * BuildingStory Shared Slice
 *
 * - **API ID**: `building_story`
 * - **Description**: BuildingStory
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BuildingStorySlice = prismic.SharedSlice<
  "building_story",
  BuildingStorySliceVariation
>;

/**
 * Primary content in *FrequentlyAsked → Default → Primary*
 */
export interface FrequentlyAskedSliceDefaultPrimary {
  /**
   * Eyebrow field in *FrequentlyAsked → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. FAQ
   * - **API ID Path**: frequently_asked.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *FrequentlyAsked → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: frequently_asked.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *FrequentlyAsked → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short supporting copy
   * - **API ID Path**: frequently_asked.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Contact CTA Label field in *FrequentlyAsked → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Still have questions? Contact us
   * - **API ID Path**: frequently_asked.default.primary.contact_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_label: prismic.KeyTextField;

  /**
   * Contact CTA Link field in *FrequentlyAsked → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where the contact CTA should go
   * - **API ID Path**: frequently_asked.default.primary.contact_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contact_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *FrequentlyAsked → Items*
 */
export interface FrequentlyAskedSliceDefaultItem {
  /**
   * Question field in *FrequentlyAsked → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Is the deposit refundable?
   * - **API ID Path**: frequently_asked.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FrequentlyAsked → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Answer to the question
   * - **API ID Path**: frequently_asked.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for FrequentlyAsked Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FrequentlyAskedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FrequentlyAskedSliceDefaultPrimary>,
  Simplify<FrequentlyAskedSliceDefaultItem>
>;

/**
 * Slice variation for *FrequentlyAsked*
 */
type FrequentlyAskedSliceVariation = FrequentlyAskedSliceDefault;

/**
 * FrequentlyAsked Shared Slice
 *
 * - **API ID**: `frequently_asked`
 * - **Description**: An accordion list of frequently asked questions.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FrequentlyAskedSlice = prismic.SharedSlice<
  "frequently_asked",
  FrequentlyAskedSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Eyebrow context field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: HERITAGE WALK UP
   * - **API ID Path**: hero_section.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Eyebrow Tag field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: EST. 1930s
   * - **API ID Path**: hero_section.default.primary.eyebrow_tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_tag: prismic.KeyTextField;

  /**
   * Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem Ipsum dolor set amet
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sub heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor set amet
   * - **API ID Path**: hero_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;

  /**
   * Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Primary CTA Label field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View Room Types
   * - **API ID Path**: hero_section.default.primary.primary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_cta_label: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.primary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA Label field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Building Story
   * - **API ID Path**: hero_section.default.primary.secondary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_cta_label: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.secondary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * image_secondary_top field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image_secondary_top
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_secondary_top: prismic.ImageField<never>;

  /**
   * image_secondary_bottom field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image_secondary_bottom
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_secondary_bottom: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *RoomsGrid → Default → Primary → rooms*
 */
export interface RoomsGridSliceDefaultPrimaryRoomsItem {
  /**
   * image field in *RoomsGrid → Default → Primary → rooms*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rooms_grid.default.primary.rooms[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *RoomsGrid → Default → Primary → rooms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Premium Loft Room Upper Level
   * - **API ID Path**: rooms_grid.default.primary.rooms[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * price field in *RoomsGrid → Default → Primary → rooms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: From HK$ 8,050
   * - **API ID Path**: rooms_grid.default.primary.rooms[].price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;

  /**
   * guests field in *RoomsGrid → Default → Primary → rooms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 1 Guest
   * - **API ID Path**: rooms_grid.default.primary.rooms[].guests
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  guests: prismic.KeyTextField;

  /**
   * beds field in *RoomsGrid → Default → Primary → rooms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 1 Bed
   * - **API ID Path**: rooms_grid.default.primary.rooms[].beds
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  beds: prismic.KeyTextField;

  /**
   * bath field in *RoomsGrid → Default → Primary → rooms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Shared Bath
   * - **API ID Path**: rooms_grid.default.primary.rooms[].bath
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bath: prismic.KeyTextField;

  /**
   * link field in *RoomsGrid → Default → Primary → rooms*
   *
   * - **Field Type**: Link
   * - **Placeholder**: View Details
   * - **API ID Path**: rooms_grid.default.primary.rooms[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *RoomsGrid → Default → Primary*
 */
export interface RoomsGridSliceDefaultPrimary {
  /**
   * eyebrow field in *RoomsGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: WHAT MAKES IT DIFFERENT
   * - **API ID Path**: rooms_grid.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * heading field in *RoomsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heritage character, not a heritage compromise
   * - **API ID Path**: rooms_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * description field in *RoomsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This address has been part of the neighbourhood far longer than the brand on the door. Here's the short version.
   * - **API ID Path**: rooms_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * rooms field in *RoomsGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: rooms_grid.default.primary.rooms[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  rooms: prismic.GroupField<Simplify<RoomsGridSliceDefaultPrimaryRoomsItem>>;
}

/**
 * Default variation for RoomsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoomsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoomsGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RoomsGrid*
 */
type RoomsGridSliceVariation = RoomsGridSliceDefault;

/**
 * RoomsGrid Shared Slice
 *
 * - **API ID**: `rooms_grid`
 * - **Description**: RoomsGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoomsGridSlice = prismic.SharedSlice<
  "rooms_grid",
  RoomsGridSliceVariation
>;

/**
 * Item in *StatStrip → Default → Primary → stats*
 */
export interface StatStripSliceDefaultPrimaryStatsItem {
  /**
   * value field in *StatStrip → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: value
   * - **API ID Path**: stat_strip.default.primary.stats[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;

  /**
   * label field in *StatStrip → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: label
   * - **API ID Path**: stat_strip.default.primary.stats[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *StatStrip → Default → Primary*
 */
export interface StatStripSliceDefaultPrimary {
  /**
   * stats field in *StatStrip → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stat_strip.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<Simplify<StatStripSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for StatStrip Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatStripSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatStripSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StatStrip*
 */
type StatStripSliceVariation = StatStripSliceDefault;

/**
 * StatStrip Shared Slice
 *
 * - **API ID**: `stat_strip`
 * - **Description**: StatStrip
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatStripSlice = prismic.SharedSlice<
  "stat_strip",
  StatStripSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BookingProcessSlice,
      BookingProcessSliceDefaultPrimary,
      BookingProcessSliceDefaultItem,
      BookingProcessSliceVariation,
      BookingProcessSliceDefault,
      BuildingStorySlice,
      BuildingStorySliceDefaultPrimaryTimelineItem,
      BuildingStorySliceDefaultPrimary,
      BuildingStorySliceVariation,
      BuildingStorySliceDefault,
      FrequentlyAskedSlice,
      FrequentlyAskedSliceDefaultPrimary,
      FrequentlyAskedSliceDefaultItem,
      FrequentlyAskedSliceVariation,
      FrequentlyAskedSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      RoomsGridSlice,
      RoomsGridSliceDefaultPrimaryRoomsItem,
      RoomsGridSliceDefaultPrimary,
      RoomsGridSliceVariation,
      RoomsGridSliceDefault,
      StatStripSlice,
      StatStripSliceDefaultPrimaryStatsItem,
      StatStripSliceDefaultPrimary,
      StatStripSliceVariation,
      StatStripSliceDefault,
    };
  }
}
