// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  booking_process: dynamic(() => import("./BookingProcess")),
  building_story: dynamic(() => import("./BuildingStory")),
  frequently_asked: dynamic(() => import("./FrequentlyAsked")),
  hero_section: dynamic(() => import("./HeroSection")),
  rooms_grid: dynamic(() => import("./RoomsGrid")),
  stat_strip: dynamic(() => import("./StatStrip")),
};
